# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Projet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QFileDialog, QLabel, QTextEdit
from PyQt5.QtGui import QPixmap
import cv2
from cv2 import *
from matplotlib.pyplot import *
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint
from matplotlib import pyplot as plt
import math
from python_speech_features import mfcc
from scipy.io.wavfile import read
from fastdtw import fastdtw
from scipy.spatial.distance import euclidean
import numpy as np
from DTW import DTW


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 563)
        MainWindow.setStyleSheet("background-color: rgb(116, 113, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 531, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.nom_audio1 = QtWidgets.QLabel(self.centralwidget)
        self.nom_audio1.setGeometry(QtCore.QRect(200, 160, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nom_audio1.setFont(font)
        self.nom_audio1.setText("")
        self.nom_audio1.setObjectName("nom_audio1")
        self.nom_audio2 = QtWidgets.QLabel(self.centralwidget)
        self.nom_audio2.setGeometry(QtCore.QRect(190, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nom_audio2.setFont(font)
        self.nom_audio2.setText("")
        self.nom_audio2.setObjectName("nom_audio2")
        self.Ouvrir_Fichier = QtWidgets.QPushButton(self.centralwidget)
        self.Ouvrir_Fichier.setGeometry(QtCore.QRect(620, 160, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Ouvrir_Fichier.setFont(font)
        self.Ouvrir_Fichier.setCheckable(False)
        self.Ouvrir_Fichier.setAutoRepeat(False)
        self.Ouvrir_Fichier.setFlat(False)
        self.Ouvrir_Fichier.setObjectName("Ouvrir_Fichier")
        self.Ouvrir_Fichier.clicked.connect(self.ouvrirAudio)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.labelDTW = QtWidgets.QLabel(self.centralwidget)
        self.labelDTW.setGeometry(QtCore.QRect(20, 310, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelDTW.setFont(font)
        self.labelDTW.setObjectName("labelDTW")
        self.DTW = QtWidgets.QLabel(self.centralwidget)
        self.DTW.setGeometry(QtCore.QRect(330, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DTW.setFont(font)
        self.DTW.setText("")
        self.DTW.setObjectName("DTW")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 340, 131, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Alignementfc)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 250, 921, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 340, 111, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.DTWfc)
        self.labelFASTDTW = QtWidgets.QLabel(self.centralwidget)
        self.labelFASTDTW.setGeometry(QtCore.QRect(20, 360, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelFASTDTW.setFont(font)
        self.labelFASTDTW.setObjectName("labelFASTDTW")
        self.FASTDTW = QtWidgets.QLabel(self.centralwidget)
        self.FASTDTW.setGeometry(QtCore.QRect(330, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FASTDTW.setFont(font)
        self.FASTDTW.setText("")
        self.FASTDTW.setObjectName("FASTDTW")
        self.labelFASTDTW_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelFASTDTW_2.setGeometry(QtCore.QRect(20, 410, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelFASTDTW_2.setFont(font)
        self.labelFASTDTW_2.setObjectName("labelFASTDTW_2")
        self.comparaison = QtWidgets.QLabel(self.centralwidget)
        self.comparaison.setGeometry(QtCore.QRect(300, 410, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comparaison.setFont(font)
        self.comparaison.setText("")
        self.comparaison.setObjectName("comparaison")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " Dynamic Time Warping (DTW):"))
        self.label_2.setText(_translate("MainWindow", "Les audios à comparer :"))
        self.label_3.setText(_translate("MainWindow", "Première Audio :"))
        self.label_4.setText(_translate("MainWindow", "Deuxième Audio :"))
        self.Ouvrir_Fichier.setText(_translate("MainWindow", "Nos fichiers .wav"))
        self.label_5.setText(_translate("MainWindow", "Résultat  :"))
        self.labelDTW.setText(_translate("MainWindow", "La distance entre les deux audios DTW :"))
        self.pushButton.setText(_translate("MainWindow", "Graphe"))
        self.pushButton_2.setText(_translate("MainWindow", "Calcul DTW"))
        self.labelFASTDTW.setText(_translate("MainWindow", "La distance entre les deux audios FASTDTW :"))
        self.labelFASTDTW_2.setText(_translate("MainWindow", "La comparaison des deux fichiers .wav :"))
    
    
    def ouvrirAudio(self):

        if( (self.nom_audio1.text() == "" and self.nom_audio2.text() == "") or ( self.nom_audio1.text() != "" and self.nom_audio2.text() != "" )):
            if( self.nom_audio1.text() != "" and self.nom_audio2.text() != "" ):
                self.nom_audio1.setText("")
                self.nom_audio2.setText("")
                self.DTW.setText("")
                self.FASTDTW.setText("")
                self.comparaison.setText("")
            filename1 = QFileDialog.getOpenFileName()   
            filename1=filename1[0]
            nom_audio=str(filename1).split("/")[-1]
            self.nom_audio1.setText(nom_audio)
        elif(self.nom_audio2.text() == ""):
            filename2 = QFileDialog.getOpenFileName()    
            #     # Ui_MainWindow.path = filename1[0]
            filename2=filename2[0]
            nom_audio=str(filename2).split("/")[-1]
            self.nom_audio2.setText(nom_audio)

    def DTWfc(self):

        if(self.nom_audio1.text() == "" or self.nom_audio2.text() == ""):
            self.comparaison.setText("aucun fichier n'a été sélectionné")
        elif(self.nom_audio1.text() != "" and self.nom_audio2.text() != ""):
            (rate1,sig1) = read(self.nom_audio1.text())
            audio1 = mfcc(sig1,rate1)
            (rate2,sig2) = read(self.nom_audio2.text())
            audio2 = mfcc(sig2,rate2)    
            dis, align = DTW(audio1, audio2) 
            distance, path = fastdtw(audio1, audio2, dist=euclidean)
            self.DTW.setText(str(dis))
            self.FASTDTW.setText(str(distance))
            if(dis<15000):
                self.comparaison.setText("identiques")
            elif(dis>15000):
                self.comparaison.setText(" pas identiques")

    def Alignementfc(self):     
        if(self.nom_audio1.text() == "" or self.nom_audio2.text() == ""):
            self.comparaison.setText("aucun fichier n'a été sélectionné")
        elif(self.nom_audio1.text() != "" and self.nom_audio2.text() != ""):
            (rate1,sig1) = read(self.nom_audio1.text())
            audio1 = mfcc(sig1,rate1)
            (rate2,sig2) = read(self.nom_audio2.text())
            audio2 = mfcc(sig2,rate2)    
            dis, align = DTW(audio1, audio2) 
            plt.plot(align)
            plt.ylabel("audio1")
            plt.xlabel("audio2")
            plt.title("Graphe d'alignement")
            plt.legend(["audio1", "audio2"], loc ="lower right")
            plt.show()
            self.comparaison.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
